- hosts: terraform-ansible
  become: true
  become_method: sudo
  tasks:
  - name: Download dotnet 6
    get_url:
      url: "https://download.visualstudio.microsoft.com/download/pr/dd7d2255-c9c1-4c6f-b8ad-6e853d6bb574/c8e1b5f47bf17b317a84487491915178/dotnet-sdk-6.0.408-linux-x64.tar.gz"
      dest: "/tmp/dotnet-sdk-6.0.408-linux-x64.tar.gz"

  - name: Extract .NET 6 SDK
    command: tar -xf "/tmp/dotnet-sdk-6.0.408-linux-x64.tar.gz" -C "/opt/dotnet"

  - name: Set .NET 6 SDK path
    lineinfile:
      path: "/etc/profile"
      line: "export PATH=\"$PATH:/opt/dotnet\""
      state: present

  - name: Check .NET 6 SDK version
    shell: /opt/dotnet/dotnet --version
    register: dotnet_version

  - name: Display .NET 6 SDK version
    debug:
      var: dotnet_version.stdout



  # - name: Install RabbitMQ
  #   apt:
  #     name: rabbitmq-server
  #     state: latest

  # - name: Enable RabbitMQ Management Plugin
  #   shell: rabbitmq-plugins enable rabbitmq_management

  # - name: Create RabbitMQ configuration directory
  #   become: yes
  #   become_user: root
  #   file:
  #     path: /etc/rabbitmq
  #     state: directory

  # - name: Create RabbitMQ configuration file
  #   become: yes
  #   become_user: root
  #   copy:
  #     dest: /etc/rabbitmq/rabbitmq.conf
  #     content: |
  #       loopback_users = none

  # - name: Start RabbitMQ service
  #   service:
  #     name: rabbitmq-server
  #     state: started
  #     enabled: true

  # - name: Install curl
  #   apt:
  #     name: curl
  #     state: present

  # - name: Wait for RabbitMQ to start
  #   wait_for:
  #     host: 127.0.0.1
  #     port: 15672
  #     delay: 10
  #     timeout: 60

  # - name: Retrieve RabbitMQ Configuration Page
  #   command: curl -s http://localhost:15672
  #   register: config_page

  # - name: Display RabbitMQ Configuration Page
  #   debug:
  #     var: config_page.stdout