- name: Configuração do .NET
  hosts: terraform-ansible
  become: true
  become_method: sudo

  tasks:
    - name: Download .NET 6 SDK
      get_url:
        url: "https://download.visualstudio.microsoft.com/download/pr/dd7d2255-c9c1-4c6f-b8ad-6e853d6bb574/c8e1b5f47bf17b317a84487491915178/dotnet-sdk-6.0.408-linux-x64.tar.gz"
        dest: "/tmp/dotnet-sdk-6.0.408-linux-x64.tar.gz"

    - name: Extract .NET 6 SDK
      unarchive:
        src: "/tmp/dotnet-sdk-6.0.408-linux-x64.tar.gz"
        dest: "/opt/dotnet"

    - name: Set .NET 6 SDK path
      lineinfile:
        path: "/etc/profile"
        line: "export PATH=\"$PATH:/opt/dotnet\""
        state: present

    - name: Load .NET 6 SDK path
      shell: . /etc/profile