- hosts: terraform-ansible
  tasks:

  - name: Configure RabbitMQ
    hosts: "{{ tf_result['outputs']['public_ip']['value'] }}"
    become: true
    gather_facts: true
    tasks:
      - name: Install RabbitMQ
        apt:
          name: rabbitmq-server
          state: latest

      - name: Configure RabbitMQ port
        lineinfile:
          dest: /etc/rabbitmq/rabbitmq.conf
          line: listener.tcp.default = 8080

      - name: Start RabbitMQ service
        service:
          name: rabbitmq-server
          state: started
          enabled: true

  # - name: instalando pacotes
  #   apt:
  #     pkg:
  #     - python3
  #     - virtualenv
  #     update_cache: yes
  #   become: yes
  # - name: Executar a bagaça
  #   copy: caminho
  # - name: criar servidor
  #   shell: "nohup busybox httpd -f -p 8081 &"
  
  # - name: Instalando dependências com pip ( podemos trocar o nome da tarefa)
  #   pip:
  #     virtualenv: /home/ubuntu/tcc/venv
  #     name:
  #       - django
  #       - djangorestframework